#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
if [[ -f recover_task_metadata.py ]]; then
	python -u recover_task_metadata.py
else
	python -u run_capsule.py "$@"
fi
