#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
if [[ -f calibration_sweep.json ]]; then
	python -u run_calibration_sweep.py
else
	python -u run_capsule.py "$@"
fi
